# Objective: 
To assess the structure, quality, completeness, and basic characteristics of the biomedical literature corpus prior to applying NLP techniques.

In [1]:
import pandas as pd
df = pd.read_csv("pubmed_medical_affairs_3layer_corpus.csv")

In [2]:
df.head()

,pmid,title,abstract,year,journal,layer
0,41483736,Intracranial activity of antibody-drug conjuga...,Antibody-drug conjugates (ADCs) represent a ra...,2025.0,Cancer treatment reviews,L1_scientific_engagement
1,41483728,Effect of quetiapine versus haloperidol on del...,"Delirium is a neuropsychiatric condition, char...",2025.0,Asian journal of psychiatry,L1_scientific_engagement
2,41483727,Vision-language models in diagnostic imaging: ...,Radiology faces an unprecedented workload cris...,2025.0,International journal of medical informatics,L1_scientific_engagement
3,41483666,The complexity of dystrophin transcription and...,Duchenne muscular dystrophy (DMD) is a rare ge...,2025.0,Neuromuscular disorders : NMD,L1_scientific_engagement
4,41483580,EEG biomarkers for a precision-medicine approa...,Major depressive disorder (MDD) is a prevalent...,2025.0,Psychiatry research. Neuroimaging,L1_scientific_engagement

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21256 entries, 0 to 21255
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pmid      21256 non-null  int64
 1   title     21214 non-null  object
 2   abstract  21256 non-null  object
 3   year      21248 non-null  float64
 4   journal   21256 non-null  object
 5   layer     21256 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 996.5+ KB

In [5]:
missing_values = df.isnull().sum()

missing_values

pmid         0
title       42
abstract     0
year         8
journal      0
layer        0
dtype: int64

In [8]:
missing_perc = ((df.isnull().sum()) / (len(df))) *100
missing_perc

pmid        0.000000
title       0.197591
abstract    0.000000
year        0.037636
journal     0.000000
layer       0.000000
dtype: float64

In [10]:
# Check for completely duplicated rows

duplicate_rows = df.duplicated().sum()
duplicate_rows

0

In [12]:
# Check for completely duplicated pmids

duplicate_pmid = df["pmid"].duplicated().sum()
duplicate_pmid

0

In [11]:
# Check for duplicate PMIDs

duplicate_titles = df["title"].duplicated().sum()
duplicate_titles

60

In [20]:
# Investigating the duplicate titles

duplicate_title_records = df[df["title"].duplicated(keep=False)].sort_values("title")

duplicate_title_records[["pmid", "title", "year", "journal", "layer"]].head(20)

,pmid,title,year,journal,layer
17027,41384609,3D,2025.0,ACS biomaterials science & engineering,L3_comparative_critical
8396,41126959,3D,2025.0,Frontiers in pharmacology,L1_scientific_engagement
12884,41122842,Advanced Life Support: 2025 International Liai...,2025.0,Circulation,L2_safety_risk
12918,41117578,Advanced Life Support: 2025 International Liai...,2025.0,Resuscitation,L2_safety_risk
987,41433764,Alzheimer's Imaging Consortium.,2025.0,Alzheimer's & dementia : the journal of the Al...,L1_scientific_engagement
988,41433740,Alzheimer's Imaging Consortium.,2025.0,Alzheimer's & dementia : the journal of the Al...,L1_scientific_engagement
989,41433458,Alzheimer's Imaging Consortium.,2025.0,Alzheimer's & dementia : the journal of the Al...,L1_scientific_engagement
16228,41433513,Alzheimer's Imaging Consortium.,2025.0,Alzheimer's & dementia : the journal of the Al...,L3_comparative_critical
16227,41434179,Alzheimer's Imaging Consortium.,2025.0,Alzheimer's & dementia : the journal of the Al...,L3_comparative_critical
385,41464967,Application of,2025.0,"Foods (Basel, Switzerland)",L1_scientific_engagement
11722,41234647,Application of,2025.0,Iranian journal of microbiology,L2_safety_risk
20046,41230178,Harnessing,2025.0,Current research in microbial sciences,L3_comparative_critical
6961,41179639,Harnessing,2025.0,Archives of Razi Institute,L1_scientific_engagement
20309,41216833,Structure-guided negative pressure wound thera...,2025.0,Journal of wound care,L3_comparative_critical
20755,41196186,Structure-guided negative pressure wound thera...,2025.0,Journal of wound care,L3_comparative_critical
21192,41176854,T,2025.0,Seminars in immunology,L3_comparative_critical
4352,41285709,T,2025.0,Nature communications,L1_scientific_engagement
16230,41433371,Technology and Dementia Preconference.,2025.0,Alzheimer's & dementia : the journal of the Al...,L3_comparative_critical
16231,41433361,Technology and Dementia Preconference.,2025.0,Alzheimer's & dementia : the journal of the Al...,L3_comparative_critical
16232,41433318,Technology and Dementia Preconference.,2025.0,Alzheimer's & dementia : the journal of the Al...,L3_comparative_critical

In [21]:
duplicte_title_records.shape

(73, 6)

In [23]:
# Check whether records with duplicate titles also have duplicate abstracts

duplicate_title_records["abstract_duplicate"] = duplicate_title_records["abstract"].duplicated(keep=False)

duplicate_title_records[duplicate_title_records["abstract_duplicate"]][["pmid", "title", "year", "journal", "layer"]].head(20)

,pmid,title,year,journal,layer
12884,41122842,Advanced Life Support: 2025 International Liai...,2025.0,Circulation,L2_safety_risk
12918,41117578,Advanced Life Support: 2025 International Liai...,2025.0,Resuscitation,L2_safety_risk
20309,41216833,Structure-guided negative pressure wound thera...,2025.0,Journal of wound care,L3_comparative_critical
20755,41196186,Structure-guided negative pressure wound thera...,2025.0,Journal of wound care,L3_comparative_critical
16233,41433272,Technology and Dementia Preconference.,2025.0,Alzheimer's & dementia : the journal of the Al...,L3_comparative_critical
16234,41433266,Technology and Dementia Preconference.,2025.0,Alzheimer's & dementia : the journal of the Al...,L3_comparative_critical
19608,41250654,The,2025.0,Journal of Korean medical science,L3_comparative_critical
364,41465382,NaN,2025.0,International journal of molecular sciences,L1_scientific_engagement

In [27]:
# Count exact duplicate title + abstract combinations

duplicate_title_abstracts = (duplicate_title_records.duplicated(subset = ["title","abstract"]).sum())
duplicate_title_abstracts

3